{% set version = "isis6" %} # synched up to isis dependencies for this version

package:
  name: libnabo
  version: {{ version }}

source:
  git_url: git@github.com:oleg-alexandrov/libnabo.git
  git_tag: {{ "bf5f327" }}
  patches:

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - boost                     1.68.0
    - eigen                     3.4.0

  run:
    - boost                     1.68.0
    - eigen                     3.4.0

test:
  commands:
  files:

about:
  home: https://github.com/ethz-asl/libnabo
  license: BSD
  summary: A fast K Nearest Neighbor library for low-dimensional spaces
  description:

extra:
  recipe-maintainers:
    - oleg.alexandrov@gmail.com
