{% set version = "isis4.4.0" %} # synched up to isis dependencies for this version

package:
  name: libnabo
  version: {{ version }}

source:
  git_url: git@github.com:ethz-asl/libnabo.git
  git_tag: {{ "2df86e0" }}
  patches:

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - boost  1.68
    - eigen  3.3.7
    - isis   4.4.0

  run:
    - boost  1.68
    - eigen  3.3.7
    - isis   4.4.0

test:
  commands:
  files:

about:
  home: https://github.com/ethz-asl/libnabo
  license: BSD
  summary: A fast K Nearest Neighbor library for low-dimensional spaces
  description:

extra:
  recipe-maintainers:
    - oleg.alexandrov@gmail.com